- name: Enable MySQL Service.
  service:
    name: "{{ role_app_mysql_service }}"
    enabled: yes

- name: start mysql
  service:
    name: "{{ role_app_mysql_service }}"
    state: restarted

- name: MySQL secure installation
  include: 31_secure_installation.yml

- name: Create DB users
  mysql_user:
    check_implicit_admin: '{{ "yes" if role_app_mysql_vault_auth_type == "auth_socket" | default(false) else omit }}'
    login_unix_socket: '{{ "/var/run/mysqld/mysqld.sock" if role_app_mysql_vault_auth_type == "auth_socket" | default(false) else omit }}'
    login_user: '{{ role_app_mysql_vault_default_auth_user if role_app_mysql_vault_auth_type == "password" | default(false) else omit }}'
    login_password: '{{ role_app_mysql_vault_auth_pw if role_app_mysql_vault_auth_type == "password" | default(false) else omit }}'
    name: '{{ item.name }}'
    password: '{{ item.pw }}'
    priv: '{{ item.priv }}'
    state: present
  loop: '{{ role_app_mysql_vault_users }}'
  when: role_app_mysql_vault_users is defined
  no_log: true
