- name: Check if root logins are configure via password
  community.mysql.mysql_query:
    login_db: INFORMATION_SCHEMA
    login_unix_socket: '{{ "/var/run/mysqld/mysqld.sock" if role_app_mysql_tmp_vault_root_auth_type  == "socket" | default(false) else omit }}'
    login_user: '{{ role_app_mysql_vault_default_auth_user }}'
    login_password: '{{ role_app_mysql_vault_auth_pw if role_app_mysql_tmp_vault_root_auth_type  == "password" | default(false) else omit }}'
    query: 'select * from mysql.user where user = "root" and host = "localhost";'
  register: role_app_mysql_tmp_check_root_localhost

- name: debug
  debug:
    var: role_app_mysql_tmp_check_root_localhost["query_result"][0][0]

- name: Fail if more than one entry for root at localhost.
  fail:
    msg: There is more than one result for root at localhost.
  when: role_app_mysql_tmp_check_root_localhost["rowcount"][0] != 1

- name: Install root logins via password, if not yet configured.
  community.mysql.mysql_query:
    login_unix_socket: '{{ "/var/run/mysqld/mysqld.sock" if role_app_mysql_tmp_vault_root_auth_type  == "socket" | default(false) else omit }}'
    login_user: '{{ role_app_mysql_vault_default_auth_user }}'
    login_password: '{{ role_app_mysql_vault_auth_pw if role_app_mysql_tmp_vault_root_auth_type  == "password" | default(false) else omit }}'
    query: 'update mysql.user set plugin = "{{ role_app_mysql_vault_root_auth_plugin }}" where user="root";'
  when: role_app_mysql_tmp_check_root_localhost["query_result"][0][0]["plugin"] != role_app_mysql_vault_root_auth_plugin

- name: Check if root logins for hosts other than localhost are configured
  community.mysql.mysql_query:
    login_db: INFORMATION_SCHEMA
    login_unix_socket: '{{ "/var/run/mysqld/mysqld.sock" if role_app_mysql_tmp_vault_root_auth_type  == "socket" | default(false) else omit }}'
    login_user: '{{ role_app_mysql_vault_default_auth_user }}'
    login_password: '{{ role_app_mysql_vault_auth_pw if role_app_mysql_tmp_vault_root_auth_type  == "password" | default(false) else omit }}'
    query: 'select * from mysql.user where user = "root" and host <> "localhost";'
  register: role_app_mysql_tmp_check_root_not_localhost

- name: debug
  debug:
    var: role_app_mysql_tmp_check_root_not_localhost["query_result"][0]

- name: Clean up root accounts
  community.mysql.mysql_query:
    login_unix_socket: '{{ "/var/run/mysqld/mysqld.sock" if role_app_mysql_tmp_vault_root_auth_type == "socket" | default(false) else omit }}'
    login_user: '{{ role_app_mysql_vault_default_auth_user if role_app_mysql_tmp_vault_root_auth_type == "password" | default(false) else omit }}'
    login_password: '{{ role_app_mysql_vault_auth_pw if role_app_mysql_tmp_vault_root_auth_type == "password" | default(false) else omit }}'
    query: "drop user \"{{ item['User'] }}\"@\"{{ item['Host'] }}\";"
  loop: '{{ role_app_mysql_tmp_check_root_not_localhost["query_result"][0] }}'
